### ISSUE TITLE
Re-license?

### ISSUE THREAD

**Issue by motin** [adevait/GmailPHP#1]
I am a long-time open source contributor and promoter, but the use of GPL is making it impossible for me to use or contribute to its development since not only do I do open source, I also sell my time as a programmer for other companies, and in those projects GPL is not an option.

Will you consider re-licensing this to LGPL, MIT or BSD or similar?

**Comment by trajchevska** [comment]
I see this is long overdue, sorry about that 🙈The license has just been changed to MIT. Thanks for your contribution!
